-- Supabase migration: create LMS tables

-- Admins table (note: in production, store hashed passwords and use Supabase Auth)
CREATE TABLE IF NOT EXISTS admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  full_name text
);

-- Materials
CREATE TABLE IF NOT EXISTS materials (
  id text PRIMARY KEY,
  title text,
  uploadDate date,
  type text,
  fileUrl text
);

-- Assignments
CREATE TABLE IF NOT EXISTS assignments (
  id text PRIMARY KEY,
  title text,
  description text,
  dueDate date,
  fileUrl text
);

-- Announcements
CREATE TABLE IF NOT EXISTS announcements (
  id text PRIMARY KEY,
  title text,
  content text,
  date date
);

-- Live classes
CREATE TABLE IF NOT EXISTS liveclasses (
  id text PRIMARY KEY,
  title text,
  date date,
  time text,
  duration int,
  link text
);

-- Students
CREATE TABLE IF NOT EXISTS students (
  id text PRIMARY KEY,
  fullName text,
  email text UNIQUE,
  regDate date
);

-- Seed an admin user (replace password with a secure hash in production)
INSERT INTO admins (username, password, full_name)
VALUES ('MR KIBE', 'kibe@123', 'Mr Kibe')
ON CONFLICT (username) DO NOTHING;
